import os
import dotenv

dotenv.load_dotenv()

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN_PROD")
TARGET_CHAT_ID = os.getenv("TARGET_CHAT_ID")
TELEGRAM_CHAT_LINK = os.getenv("TELEGRAM_CHAT_LINK")
LINKED_CHAT_ID = os.getenv("LINKED_CHAT_ID")

STRIPE_WEBHOOK_HOST=os.getenv("STRIPE_WEBHOOK_HOST", "localhost")
STRIPE_WEBHOOK_PORT=os.getenv("STRIPE_WEBHOOK_PORT")

SCHEDULER_HOUR=os.getenv("SCHEDULER_HOUR", 14)
SCHEDULER_MINUTE=os.getenv("SCHEDULER_MINUTE", 00)

BAN_HOUR = os.getenv("BAN_HOUR", 23)
BAN_MINUTE = os.getenv("BAN_MINUTE", 00)